### ISSUE TITLE
Не загружается контент (оглавление?) на сайте

### ISSUE THREAD

**Issue by c01nd01r** [nauchikus/typescript-definitive-guide#107]
404 https://nauchikus.github.io/typescript-definitive-guide/book/contents.json

**Comment by loosefer** [comment]
[В этом PR](https://github.com/nauchikus/typescript-definitive-guide/pull/106/files) я менял имя файла, возможно проблема в этом

**Comment by nauchikus** [comment]
@loosefer дело имеено в этом! Изменение имя файла требует его изменения и в contents.json по которому (пока) сборка происходит.
