### ISSUE TITLE
Не работают кнопки скопировать url

### ISSUE THREAD

**Issue by nauchikus** [nauchikus/typescript-definitive-guide#12]
В книге неработают кнопки скопировать url подглавы.

**Comment by Alendorff** [comment]
Это всё ещё не работает кстати. При нажатии на кнопочку ничего не происходит:

![image](https://user-images.githubusercontent.com/4989157/53964764-98bb7580-40f8-11e9-9162-2ab38e1868a3.png)

_Ещё неудобный момент что нет вертикальной прокрутки при чтении. Но это не про то._

**Comment by nauchikus** [comment]
@Alendorff обязательно поправлю. 

> Ещё неудобный момент что нет вертикальной прокрутки при чтении. Но это не про то.
Вы имеете ввиду что в самой книге нет скроллбара? Если вы об этом, то он насамом деле есть, просто из-за того что кастомный и из-за самой идеи сдвигать контент без его адаптации, уходт в бок. Меня это тоже не радует, поэтому тоже исправлю, как будет время.

**Comment by nauchikus** [comment]
@Alendorff кнопку скопировать, исправил, хотя чувство неудовлетворенности оталось, так как сама кнопка нативная для html и не вписывается в основной дизайн. Будет время и это исправлю. А неудобство возникающее из-за неотображения скроллбара исправлю в ближайшее время.
