### ISSUE TITLE
Не работает на Firefox

### ISSUE THREAD

**Issue by Realetive** [nauchikus/typescript-definitive-guide#141]
![Снимок экрана 2020-08-05 в 21 17 37](https://user-images.githubusercontent.com/2073959/89495964-1427c780-d7c2-11ea-9e53-ed9ca6979481.png)

OSX 10.13.6

Предполагаю, что проблема во встроенной «Улучшенной защите от отслеживания».

**Comment by nauchikus** [comment]
@Realetive спасибо что сообщили. С сегодняшнего дня официально безработный, поэтому первым делом доделую новый сайт. Потом возвращусь к этому вопросу. Хотя уже сейчас могу сказать, что если дело в отслеживании, то уменя кроме яндекс.метрики ничего вроде там и нет.. FF не может же все сайты с ЯМ блочить?

**Comment by Realetive** [comment]
Отключил «Защиту»:

![Снимок экрана 2020-08-06 в 15 43 12](https://user-images.githubusercontent.com/2073959/89533088-836ddd80-d7fb-11ea-9ff5-1e3f00dd9ea9.png)

**Comment by Realetive** [comment]
Похоже, это моя локальная проблема (расширения), потому что в инкогнито всё заработало.
