### ISSUE TITLE
Картника type-conversion-double-to-int.png пропала

### ISSUE THREAD

**Issue by denis-komarov** [nauchikus/typescript-definitive-guide#145]
В разделе:
[Явные Преобразования](https://nauchikus.github.io/typescript-definitive-guide/book/chapters/preobrazovanie%20tipov)
ссылка на картинку не работает. В PDF, соответственно, картинки тоже нет.

**Comment by nauchikus** [comment]
@denis-komarov исправил. Спасибо за замечание.
