### ISSUE TITLE
Глава 16.1 опечатка в коде примера

### ISSUE THREAD

**Issue by Dmytro-Uchkin-BlueCrew** [nauchikus/typescript-definitive-guide#150]
Нужно сменить оператор с `|` на `&`
![image](https://user-images.githubusercontent.com/72198316/99315852-fe6b7900-286b-11eb-8e0f-53f2ade7f538.png)

**Comment by nauchikus** [comment]
@Dmytro-Uchkin-BlueCrew спасиюо за помощь! На текущей момент, эта ошибка уже исправлена, у вас, видимо, старая вресия книги.
