### ISSUE TITLE
Сломанный typescript - разный результат выполнения кода из примера spread'а в tuple'ах на разных версиях typescript'а

### ISSUE THREAD

**Issue by antixrist** [nauchikus/typescript-definitive-guide#152]
Цитата из [главы про кортежи](https://github.com/nauchikus/typescript-definitive-guide/blob/6b5dc385bef0ab00c064331d721bbde3d7c8bb3c/book/ru/chapters/019.(%D0%A2%D0%B8%D0%BF%D1%8B)%20Object%2C%20Array%2C%20Tuple/content.md#tuple-t0-t1--tn-%D1%82%D0%B8%D0%BF-%D0%BA%D0%BE%D1%80%D1%82%D0%B5%D0%B6):

> Когда `spread` применяется к типу без известной длины (обычный массив `...number[]`), то тип получаемый в результате также становится неограниченным и все типы следующие после такого распространения (обычный массив) образуют с ним тип объединение (`Union`).
> ```ts
> type Strings = [string, string];
> type BooleanArray = boolean[];
>
> // type Unbounded0 = [string, string, ...(boolean | symbol)[]]
> type Unbounded0 = [...Strings, ...BooleanArray, symbol];
>
> // type Unbounded1 = [string, string, ...(string | boolean | symbol)[]]
> type Unbounded1 = [ ...Strings, ...BooleanArray, symbol, ...Strings]
> ```

Как [гласит документация](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-0.html#variadic-tuple-types) - это работает, начиная с версии 4.0: [play](https://www.typescriptlang.org/play?ts=4.0.5#code/C4TwDgpgBAysBOBLAdgcwM5QLxQNroRVQBooCk0BdAKFEigCEB7JgGwgENkBBeeDkNigAjFuy64a1APTSodaAFVkogK7IAJhA0AGIfkJpS5IqQB0FgBSi2nZFAA+ZEAFtRrAJSSaCqMrWa2no4uBZmcBQY5hbMtly8-CDGru5SsvLgSipM6loaAIz6JkZkhiRQYZbFqI4iYna16ClsXpQ+mX7ZudqFIRUWEUTo0Wax4jx8AslubCODaOg0QA).

Но в версии 4.1, разрабы ts похоже что-то поломали и этот пример выдаёт ошибку `TS1256: A rest element must be last in a tuple type` (т.е. вернулось [поведение до версии 4.0](https://www.typescriptlang.org/play?ts=3.9.7#code/C4TwDgpgBAysBOBLAdgcwM5QLxQNroRVQBooCk0BdAKFEigCEB7JgGwgENkBBeeDkNigAjFuy64a1APTSodaAFVkogK7IAJhA0AGIfkJpS5IqQB0FgBSi2nZFAA+ZEAFtRrAJSSaCqMrWa2no4uBZmcBQY5hbMtly8-CDGru5SsvLgSipM6loaAIz6JkZkhiRQYZbFqI4iYna16ClsXpQ+mX7ZudqFIRUWEUTo0Wax4jx8AslubCODaOg0QA)): [play](https://www.typescriptlang.org/play?ts=4.1.3#code/C4TwDgpgBAysBOBLAdgcwM5QLxQNroRVQBooCk0BdAKFEigCEB7JgGwgENkBBeeDkNigAjFuy64a1APTSodaAFVkogK7IAJhA0AGIfkJpS5IqQB0FgBSi2nZFAA+ZEAFtRrAJSSaCqMrWa2no4uBZmcBQY5hbMtly8-CDGru5SsvLgSipM6loaAIz6JkZkhiRQYZbFqI4iYna16ClsXpQ+mX7ZudqFIRUWEUTo0Wax4jx8AslubCODaOg0QA).

Может быть стоит сделать об этом ремарку в данном абзаце книги?

**Comment by nauchikus** [comment]
Да, действительно.. Но дело в том, что сейчас просто нет возможности во всем разобраться. Упоминать об этом не стоит, но если поведение действительно было обращено, что непременно станет известно после ещё нескольких версий, то я перепишу. Несоответствие, не часто, но бывает.

**Comment by antixrist** [comment]
Нашёл issue на эту тему: https://github.com/microsoft/TypeScript/issues/41701#issuecomment-752990393

**Comment by nauchikus** [comment]
@antixrist в версии 4.2 обсуждаемое поведение было измененно [Изменение поведения указания остаточных типов в кортеже](https://typescript-definitive-guide.ru/what-is-new/4.2#Izmenenie_povedeniya_ukazaniya_ostatochnyh_tipov_v_korteje).
