### ISSUE TITLE
Ошибка при первой загрузке

### ISSUE THREAD

**Issue by pepelsbey** [nauchikus/typescript-definitive-guide#177]
Если открыть главную страницу первый раз в любом браузере (Chrome, Firefox, Safari), то вместо контента — ошибка. При этом можно открыть страницы во вкладках, снова перейти на главную и всё станет видно. Но при первой загрузке — такое. Легко проверить в приватной вкладке.

> Application error: a client-side exception has occurred (see the browser console for more information).

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/105274/166433636-ed3892d0-c00f-46c9-8575-72443ad2c63b.png">

**Comment by nauchikus** [comment]
@pepelsbey проверил в chrome (режим инкогнито) - работает.

**Comment by pepelsbey** [comment]
Есть подозрение, что дело либо в регионе, либо в AdBloker: я открываю ссылку из Германии и ссылка на файл счётчика возвращает 400, аналогично ведут себя браузеры, где есть AdBlocker. Кажется это и валит приложение, что конечно неправильно.

Это Chrome, без AdBlocker:

<img width="882" alt="image" src="https://user-images.githubusercontent.com/105274/166638513-c0de89d2-15b3-4318-b6c3-c6ea26f0b453.png">

<img width="371" alt="image" src="https://user-images.githubusercontent.com/105274/166638449-1eb2b3e5-b339-4f69-a82f-d95a3a0f5533.png">

Это Firefox с AdBlocker

<img width="1168" alt="image" src="https://user-images.githubusercontent.com/105274/166638896-a6985532-f354-410d-aeca-19b7faf4b9f0.png">

Это Safari с AdBlocker

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/105274/166638950-c2256da0-c423-4eb0-a638-f0bcf8b90477.png">

**Comment by nauchikus** [comment]
@pepelsbey с вами нельзя не согласится, краш приложения из-за ошибки, это неправильно и. Когда будет время я посмотрю.
По поводу региона мне тоже мысль приходила. Но мне кажется, что если бы она была верна, то при повторном заходе ошибка бы повторялась. У вас при отсутствии ошибки поисковик вообще работает?

По поводу adblick... Мне кажется мало вероятно, что поисковик внесен в глобальный блок, поскольку он установлен на все опенсоурс документации.

**Comment by nauchikus** [comment]
@pepelsbey сейчас у вас работает?

**Comment by pepelsbey** [comment]
Да, кажется починилось!

**Comment by Anastasiia26100** [comment]
> Да, кажется починилось!

так а как починить?
