### ISSUE TITLE
Диаграмма Иерархия наследования (глава 11)

### ISSUE THREAD

**Issue by Pomar81** [nauchikus/typescript-definitive-guide#36]
направление стрелок связей parent-child и child-parent инверсное

**Comment by nauchikus** [comment]
@Pomar81 путанницу со стрелками (и кстате с определением в самом тексте) смог заметить только для отношений родитель-ребенок и уже исправил. Если есть что-то ещё, говорите, я не заметил. И отдельное спасибо за повышенную внимательность.

**Comment by Pomar81** [comment]
В тексте изменения применились а на диаграмме нет

**Comment by nauchikus** [comment]
@Pomar81 если текст поменялся, а картинка нет, то скорее всего, это дело в хешировании браузера. Мне стыдно признаться, но об этой проблеме я давно знаю, сам намучался, но никак руки не дойдут до изменения конфига webpack. У меня браузер показывает измененную картинку - синяя стрелка `bottom -> top`, оранжевая `top -> bottom`.

**Comment by Pomar81** [comment]
![image](https://user-images.githubusercontent.com/16816506/57128127-1fa86980-6d9b-11e9-853d-2c089ec75dbb.png)

**Comment by nauchikus** [comment]
@Pomar81 заметил это уже после того, как оставил комментарий, который удалил. Так спешил исправит, что изменил цвет только снизу :)
