### ISSUE TITLE
Битые ссылки

### ISSUE THREAD

**Issue by Luchanso** [nauchikus/typescript-definitive-guide#5]
При попытке перейти по ссылкам внизу [страницы](https://nauchikus.github.io/typescript-definitive-guide/book/contents/Tipy-Type-Queries-zaprosy-tipa-Alias-psevdonimy-tipa) переходит по ссылке: `https://nauchikus.github.io/book/contents/Rasshirennye-tipy-Readonly-Partial-Required-Pick-Record`, которая ведёт на 404

Спасибо за книгу - очень легко читается, достаточно ёмко и без воды 👍

**Comment by Luchanso** [comment]
Это воспроизводится только, когда пытаешься открыть ссылку в новом окне, если открывать в том же окне то всё окей.

**Comment by nauchikus** [comment]
@Luchanso спасибо, не знал. Это все из-за отсутствия нормального домена. Без него невозможно исправить сохранив здравый смысл. В ближайшее время исправлю.

> Спасибо за книгу - очень легко читается, достаточно ёмко и без воды +1
Очень рад что Вам понравилось.

**Comment by sozzzzz** [comment]
Судя по всему после этого фикса перестали работать внешние ссылки.
Например в разделе 
https://nauchikus.github.io/typescript-definitive-guide/book/contents/Deklaracii/Ustanovka-deklaracii-s-pomoshchu-types 
ссылка на сайт TypeSearch

**Comment by nauchikus** [comment]
Сомневаюсь что дело в фиксе. Скорее всего ссылка была не рабочей всегда, так как создать подобное её поведение подсилу лишь сборщику. В ближайшее время устраню недостаток. Спасибо большое за помощь, я очень Вам признателен.03.03.2019, 06:57, "sozzzzz" <notifications@github.com>:Судя по всему после этого фикса перестали работать внешние ссылки.
Например в разделе
https://nauchikus.github.io/typescript-definitive-guide/book/contents/Deklaracii/Ustanovka-deklaracii-s-pomoshchu-types
ссылка на сайт TypeSearch

**Comment by nauchikus** [comment]
@sozzzzz это починили.

**Comment by isSteel** [comment]
На сайте при наведении на логотип во всплывающей подсказке опечатка, пишу здесь что бы новый вопрос не открывать.

За материал большое спасибо, лучшее что есть на русском для тех, кто предпочитает текстовый формат вместо видео.

**Comment by nauchikus** [comment]
@isSteel действительно опечатка! Сейчас исправлю. Спасибо за помощь и обратную связь по самой книге.
