### ISSUE TITLE
Будет ли pdf версия книги?

### ISSUE THREAD

**Issue by vadim-96** [nauchikus/typescript-definitive-guide#55]

**Comment by nauchikus** [comment]
Меня вдохнавляет идея развития идеи, но реальность такова что не совпадает с желаемым, попросту не хватает времени. В планах есть полность переработать сам сайт, сделать его более доступным и интерактивным. И pdf вписывается в концепцию доступности, но обещать не буду, так как никогда не генерировал сложных pdf  и не знаю может ли из-за интерактивности возникнуть какие-то сложности, которые придется решать написанием собственных библиотек, накоторые уходит много времение и которого попросту нет.

**Comment by nauchikus** [comment]
@vadim-96 а можно поинтересоваться, почему именно pdf? В чем проблема с чтением вэб-версии?

**Comment by vadim-96** [comment]
@nauchikus pdf'ку можно открыть оффлайн, скачать в читалку или смарт. И мне кажется это просто удобно, чем читать на сайте в браузере.

**Comment by nauchikus** [comment]
@vadim-96 полностью согласен с Вами! Просто подумал что есть что-то о чем я пока не знаю.

**Comment by Reactiver** [comment]
Pdf можно сделать в LaTex. Я так диплом делал. Получается очень даже прилично.

**Comment by denis-komarov** [comment]
Подготовил pdf файл книги – это довольно точный слепок текущей версии, размещенной в web. 
Что есть специфичного для pdf:
- Иерархическое содержание книги с разбивкой на главы первого и второго уровней. Такое содержание доступно в левой панели стандартных программ для просмотра pdf (типа Sumatra PDF, Adobe Acrobat Reader).
- Все внутренние ссылки (ссылки на текст в самой книге) работают, т.е. клик по ссылке приводит в программе для просмотра pdf к переходу на соответствующий текст.
- Стиль оформления текста максимально воспроизводит стиль оформления web версии.
- Отступы 5 мм на страницах для максимального использования площади экрана при чтении с мобильного устройства.
- В метаданных файла pdf указан автор - https://github.com/nauchikus/typescript-definitive-guide

**Comment by nauchikus** [comment]
@denis-komarov естественно я вам очень благодарен за проделанную немалую работу, вот только есть один момент который подпортит впечатление. Проще говоря pdf-ка не нужна. Уже вышла версия 3.9 для которой обновлен раздел _what-is-new_ и после того как я поправлю текущий сайт, я обновлю контент самой книги. Правда там пару строчек, но это уже намекает, что она постоянно меняется. Поэтому требуется автоматическая генерация, которую сделать очень просто и которой я займусь после того, как через пару недель выложу полностью переписанный сайт. Поэтому я просто не хочу выделять время (которого катастрофически мало) на добавления ссылок в текущее приложение.

Новая версия будет на реакте и после обновления я сообщу об этом в телеграмме. Очень надеюсь на помощь в отлаживании багов! Ведь время у самого нет. Тем более это замечательная практика, так как все написано на typescript. 

И Вам ещё раз спасибо за проделанную работу! Если бы этот момент случился год назад, то осчастливил бы многих.

**Comment by denis-komarov** [comment]
А это и есть продукт автоматической генерации. Если web версия книги (в ее нынешнем виде) будет обновлена, то я в тот же день я выпущу pdf версию. Но если автор хочет заняться этим сам и в основной ветке это никому не нужно, то Ок, просто оставлю у себя, кому-нибудь да пригодится.

**Comment by denis-komarov** [comment]
Выложил pdf файл книги для текущей версии 4.0.

**Comment by nauchikus** [comment]
@denis-komarov скажите, а вашу реализацию можно выполнить в github actions или она требует ручного вмешательства (что именно?)?
