### ISSUE TITLE
Вопрос по главе Базовый Тип Any

### ISSUE THREAD

**Issue by dartess** [nauchikus/typescript-definitive-guide#58]
> В случае, если при объявлении переменных var и let, а также полей объекта созданного с помощью литерала объекта { } и полей объявленных в теле класса, не было присвоено значение, то компилятором будет выведен тип данных Any.

После этого приведён пример с переменными и полями класса. Что имелось в виду под литералом объектом? Насколько я знаю, нельзя у литерала не задать значение поля, а значит, значение будет выведено как и в случае присвоения значения переменной при объявлении.

**Comment by nauchikus** [comment]
@dartess не имеею ни малейшего представления о чем я мог думать в момент когда писал такую ерунду :) Спасибо за замечание.

**Comment by dartess** [comment]
@nauchikus я тут вычитывать пытаюсь, потому что читать довольно трудно. Некоторые вещи без знания темы вообще не понятны.

Например: 

> Типы - Примитивные типы Null, Undefined, Void, Never, Unknown

> Тип `unknown` при операциях с сопоставленных типах представляется объектным типом `{}`

" при операциях с сопоставленных типах " — сложно, сложно, непонятно т.т

**Comment by nauchikus** [comment]
@dartess это нормальное являение. Сначала пишется предложение водном склонении, затем приходит осознание, что его часть необходимо переписать. Новая часть имеет другое склонение, но так как большая часть предложения совпадает, то мозг попросту не замечает разницы и при контрольнойпроверке читает его не таким какое оно есть, а таким каким его хочет видеть.

Решение только одно, либо читать спустя много время, либо давать читать кому-то ещё. У меня нет время на перечитывание. Кроме того уровень обнаружения собственных ошибок очень мал.
 
Поэтому если вам встретелось подобное, не ленитесь, пишите прям сюда, я сам исправлю. Или по желанию можете сами исправить, поскольку времени может быть затрачено даже меньше чем уйдет на описание ошибки.

Кроме того, если что-то написано трудно, непонятно, сложно, ерундово - то тоже пишите. К примеру вы написали об одной ошибки, а я вместе с ней полностью переписал ещё одну тему, так как даже сам не понял что хотел сказать много лет назад.

Кроме того, вы указали на факт нарушения последовательности при изучении материала, которого я очень сильно стрался избежать при написании. И дело в том, что тип `unknown` появился спустя много лет после написания этого хелпа и я попросту не учел этого факта. Я этот момент обозначил и даже хотел вынести в отдельную главу, но факт настолько незначительный что передумал.

**Comment by dartess** [comment]
@nauchikus спасибо за развёрнутый ответ. Ещё раз повторюсь, я сейчас вычитываю, в основном по пунктуации и оформлению, иногда — стилистические правки (когда не сразу удаётся понять, о чём речь). Как закончу, пульну одним реквестом.

Если что-то совсем не понятное, буду писать сюда.
