### ISSUE TITLE
Пример по бивариантности

### ISSUE THREAD

**Issue by dartess** [nauchikus/typescript-definitive-guide#82]
Здравствуйте! Пример по бивариантности в главе `Типизация в TypeScript`, видимо, не совсем корректный:

```
interface IAnimal { type: string; }
interface IBird extends IAnimal { fly(): void; }

function f0( p: IAnimal ): void {}
function f1( p: IBird ): void {}


type T0 = typeof f0;
type T1 = typeof f1;


let v0: T0 = f1; // Ok
let v1: T1 = f0; // Ok
```

Получаю в таком случае ошибку в v0:
```
TS2322: Type '(p: Bird) => void' is not assignable to type '(p: Animal) => void'.
   Types of parameters 'p' and 'p' are incompatible.
     Property 'fly' is missing in type 'Animal' but required in type 'Bird'.
```

TS 3.7.2

**Comment by nauchikus** [comment]
@dartess да! Есть такое момент. Дело в том, что множестово особенностей о которых полезно знать разработчикам достпуны лишь за флагами компилятора, о чем я забыл упомянуть в конкретном случае. С вашей помощью этот момент исправлен за что очень благодарен. Если вашему вниманию откроются ещё ускользнувшие от меня детали, сразу сюда!
